# Generated by Django 4.1.2 on 2022-11-10 16:42

import advert.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'Значение не может быть менее 5 символов')])),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(null=True)),
                ('is_published', models.BooleanField(validators=[advert.validators.bool_valid])),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
