# Generated by Django 4.1.2 on 2022-11-11 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='name',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'Значение не может быть менее 10 символов')]),
        ),
    ]
