# Generated by Django 4.1.2 on 2022-11-11 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0003_alter_advert_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
