# Generated by Django 4.1.2 on 2022-11-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0005_alter_advert_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
