# Generated by Django 4.1.2 on 2022-10-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_func', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
