# Generated by Django 4.1.2 on 2022-10-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ManyToManyField(null=True, related_name='rel_skills', to='user.location', verbose_name='Location list'),
        ),
    ]
