# Generated by Django 4.1.2 on 2022-11-10 17:15

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(validators=[user.validators.age_valid]),
        ),
    ]
