version: '3.8'

services:
  app:
    build:
      context: .
    command: python manage.py runserver localhost:8000
    ports:
      - 8000:8000
    restart: always
  db:
    image: postgres:12.4-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: skypro_l27
      POSTGRES_PASSWORD: skypro_l27
      POSTGRES_DB: skypro_l27
    restart: always
    ports:
    - "5432:5432"

volumes:
  postgres_data: